name: CompatHelper

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily

jobs:
  CompatHelper:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8' # Minimum supported version

      - name: Install CompatHelper
        run: julia --project -e 'using Pkg; Pkg.add("CompatHelper"); using CompatHelper'

      - name: Run CompatHelper
        run: julia --project -e 'using CompatHelper; CompatHelper.main()'
