name: CompatHelper

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  compathelper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'  

      - name: Install CompatHelper
        run: julia --project=@. -e 'using Pkg; Pkg.add("CompatHelper")'

      - name: Run CompatHelper
        run: julia --project=@. -e 'using CompatHelper; CompatHelper.main()'
