name: TagBot

on:
  schedule:
    - cron: "0 0 * * *"  # daily
  workflow_dispatch:
  release:
    types: [published]

jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run TagBot
        uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
