name: TagBot

on:
  push:
    tags:
      - 'v*'

jobs:
  TagBot:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.8' # Minimum supported version

      - name: Install TagBot
        run: julia --project -e 'using Pkg; Pkg.add("TagBot"); using TagBot'

      - name: Run TagBot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project -e 'using TagBot; TagBot.main()'
